import sys
import os
from pathlib import Path

# Add project root to sys.path to allow importing from shared
sys.path.append(str(Path(__file__).parent.parent))

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Response
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
import json
import asyncio
import logging
import io
import zipfile
from agents.orchestrator import orchestrator
from shared.schemas import ProjectExportRequest

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("DevPilot")

app = FastAPI(title="DevPilot API")

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "DevPilot API is running"}

@app.post("/api/export")
async def export_project(request: ProjectExportRequest):
    """
    Generates a ZIP file containing the generated project artifacts.
    """
    logger.info("Generating project export ZIP")
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        # 1. Documentation
        zip_file.writestr("docs/PRD.md", request.prd)
        zip_file.writestr("docs/architecture.md", request.architecture)
        zip_file.writestr("docs/database.sql", request.database_schema)
        zip_file.writestr("docs/QA_checklist.md", request.qa_checklist)
        
        # 2. Backend Scaffold
        zip_file.writestr("backend/main.py", request.backend_code)
        zip_file.writestr("backend/requirements.txt", "fastapi\nuvicorn\npydantic\n")
        
        # 3. Frontend Scaffold
        zip_file.writestr("frontend/src/App.tsx", request.frontend_code)
        
        # 4. Root files
        zip_file.writestr("README.md", f"# Generated Project\n\nGenerated by DevPilot.\n\n## PRD\n{request.prd}")
        zip_file.writestr("docker-compose.yml", "version: '3.8'\nservices:\n  app: { build: . }")

    zip_buffer.seek(0)
    return StreamingResponse(
        zip_buffer, 
        media_type="application/x-zip-compressed",
        headers={"Content-Disposition": f"attachment; filename=devpilot_project.zip"}
    )

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    logger.info("WebSocket connection established")
    try:
        while True:
            data = await websocket.receive_text()
            message = json.loads(data)
            logger.info(f"Received message: {message}")
            
            if message.get("type") == "start_workflow":
                idea = message.get("idea")
                config = message.get("config", {}) # Catch settings payload from user
                
                state = {
                    "idea": idea,
                    "prd": "",
                    "market_research": "",
                    "architecture": "",
                    "database_schema": "",
                    "backend_code": "",
                    "frontend_code": "",
                    "qa_checklist": "",
                    "reviewer_critique": "",
                    "current_agent": "",
                    "logs": [],
                    "config": config # Set config context in state graph
                }
                
                async for event in orchestrator.astream(state):
                    node_name = list(event.keys())[0]
                    node_data = event[node_name]
                    agent_name = node_data.get("current_agent", node_name)
                    logs_to_send = node_data.get("logs", [])
                    
                    # Stream logs typewriter-style for high visual fidelity
                    for log_msg in logs_to_send:
                        await websocket.send_text(json.dumps({
                            "type": "agent_update",
                            "agent": agent_name,
                            "logs": [log_msg],
                            "status": "running"
                        }))
                        await asyncio.sleep(0.5) # Dynamic logging pause
                    
                    # Send agent completion update
                    await websocket.send_text(json.dumps({
                        "type": "agent_update",
                        "agent": agent_name,
                        "logs": logs_to_send,
                        "status": "completed"
                    }))
                    
                    # Send partial state update (only sending keys that were actually updated in this node)
                    state_update = {}
                    for key in ["prd", "market_research", "architecture", "database_schema", "backend_code", "frontend_code", "qa_checklist", "reviewer_critique"]:
                        if key in node_data and node_data[key]:
                            state_update[key] = node_data[key]
                    state_update["current_agent"] = agent_name

                    await websocket.send_text(json.dumps({
                        "type": "state_update",
                        "state": state_update
                    }))

                await websocket.send_text(json.dumps({
                    "type": "workflow_complete",
                    "message": "Project generation finished."
                }))
                
    except WebSocketDisconnect:
        logger.info("WebSocket connection closed by client")
    except Exception as e:
        logger.error(f"Critical WebSocket error: {e}", exc_info=True)
        try:
            # Notify the frontend of the specific error
            await websocket.send_text(json.dumps({
                "type": "error", 
                "message": f"Engine Error: {str(e)}"
            }))
        except Exception as send_error:
            logger.error(f"Failed to send error message to websocket: {send_error}")
        
        # We close the connection on critical errors to allow the frontend's 
        # reconnection logic to kick in and reset the state.
        await websocket.close()

if __name__ == "__main__":
    import uvicorn
    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8001"))
    uvicorn.run("main:app", host=host, port=port, reload=True)
